### PR TITLE
Hotfix v2.1.2 2 golden

### PR DESCRIPTION
**Pull request by nuttycom**
This adds a golden test for node start on network upgrade, but it is not currently passing with the inclusion of the 4496-heartwood-chain-consistency branch.

### CODE REVIEW

**Comment by nuttycom** [comment]
This has now been updated to base its commits only on tags, not the errant hotfix-v2.1.2-1 branch that had `master` merged to it. However, it's still getting the following error on startup:
```
zcashd: main.cpp:2604: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, const CChainParams&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.
ERROR:root:An error occurred attempting to start node 1
Unexpected exception caught during testing: bitcoind exited with status -6 during initialization
  File "/home/nuttycom/work/zcash/qa/rpc-tests/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "/home/nuttycom/work/zcash/qa/rpc-tests/upgrade_golden.py", line 77, in run_test
    self.nodes[i] = start_node(i, self.options.tmpdir, extra_args=last_upgrade.extra_args)
  File "/home/nuttycom/work/zcash/qa/rpc-tests/test_framework/util.py", line 308, in start_node
    wait_for_bitcoind_start(bitcoind_processes[i], url, i)
  File "/home/nuttycom/work/zcash/qa/rpc-tests/test_framework/util.py", line 155, in wait_for_bitcoind_start
    raise Exception('bitcoind exited with status %i during initialization' % process.returncode)
```

**Comment by daira** [comment]
I rebased this and I'm currently investigating the test failure.

**Comment by nuttycom** [comment]
The test is now passing.

**Comment by daira** [comment]
Is this targeting the right branch?

**Pull request closed without merging**
